//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDBEntities : DbContext
    {
        public AppDBEntities()
            : base("name=AppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<CarUser> CarUsers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<SpotAvailibility> SpotAvailibilities { get; set; }
        public virtual DbSet<SpotUser> SpotUsers { get; set; }
    }
}
