//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int spotID { get; set; }
        public System.DateTime dateAvailable { get; set; }
        public System.TimeSpan startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<decimal> hourlyRate { get; set; }
        public Nullable<int> paymentID { get; set; }
        public int carID { get; set; }
    
        public virtual SpotAvailibility SpotAvailibility { get; set; }
        public virtual CarUser CarUser { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
