//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpotUser()
        {
            this.SpotAvailibilities = new HashSet<SpotAvailibility>();
        }
    
        public int spotID { get; set; }
        public Nullable<int> userID { get; set; }
        public string spotType { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public string postalCode { get; set; }
        public string details { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpotAvailibility> SpotAvailibilities { get; set; }
    }
}
