//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotAvailibility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpotAvailibility()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int spotID { get; set; }
        public System.DateTime dateAvailable { get; set; }
        public System.TimeSpan startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<decimal> hourlyRate { get; set; }
        public Nullable<decimal> minBooking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual SpotUser SpotUser { get; set; }
    }
}
